### ISSUE TITLE
Missing package?

### ISSUE THREAD

**Issue by ghost** [gncs/molgym#1]
Hello,

 When I tried: scripts\run.py --name=ch4o --formulas=CH4O --canvas_size=10 --num_steps_per_iter=384 --num_iters=300 --save_rollouts=eval --min_mean_distance=0.95 --max_mean_distance=1.80 --seed=1

  I got:
  molgym-master\scripts\molgym\calculator.py", line 1, in <module>
    from scine_sparrow import Calculation
ModuleNotFoundError: No module named 'scine_sparrow'

   Thanks for your help!

     Wei

**Comment by rpinsler** [comment]
Hi Wei,

As stated in the readme, the package depends on [Sparrow 2.0.1](https://github.com/qcscine/sparrow/releases/tag/2.0.1). `scine-sparrow` is the python binding of Sparrow. See the [manual](https://scine.ethz.ch/static/download/manuals/v2.0.1/sparrow_manual.pdf) for installation instructions.

Best,
Robert

**Comment by ghost** [comment]
Thanks @rpinsler Robert! I will try to install it.

**Comment by diamondspark** [comment]
@rpinsler I downloaded the zip from above linked Sparrow 2.0.1. How do I install it? Any pointers?
Thank You!
