### ISSUE TITLE
Provide tags for versions

### ISSUE THREAD

**Issue by awvwgk** [gncs/molgym#12]
Thanks for this interesting project. Is it possible to provide tagged releases for this project?

This would make it easier to identify version like v1.0 (fbb2910549f4e80af3743f612a9170b8fa8666b6) or v2.0 (6ffc42e7785538ea5406e58271a12060dcd3e059) and also provides better ways to reference those version in the upstream repository when installing or packaging it.

**Comment by gncs** [comment]
I appreciate your interest in our project, @awvwgk. Done :)
