### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by awvwgk** [gncs/molgym#13]
I just noticed that this project doesn't have an open source license. I'm interested in testing this package and would much appreciate if you could clarify the project license.

**Comment by gncs** [comment]
Fixed in 3c7d4858e6ad5615abcd41b2f23f50dbc929e294.

**Comment by awvwgk** [comment]
Thanks.

**Comment by jebert-1** [comment]
can you share license key , when i tried to run the code a warning message shown.
Warning: Unable to find valid license for product ID 06b7db1d-5a40-4d2c-b89c-6b1887c377c1.
