### ISSUE TITLE
Sparrow Update - Fail to import 'Calculation'

### ISSUE THREAD

**Issue by asaghafi** [gncs/molgym#8]
Hi there!
Any idea how to fix this import error? It is probably due to upgrade of sparrow from 2.01 to 3.0.0. This was generated after running the scripts/run.py \ ... . 

File "/root/molgym/molgym/calculator.py", line 1, in <module>
    from scine_sparrow import Calculation
ImportError: cannot import name 'Calculation' from 'scine_sparrow' (/root/sparrow/install/lib/python3.9/site-packages/scine_sparrow/__init__.py)

**Comment by gncs** [comment]
Thank you for reaching out. Unfortunately, molgym currently only supports Sparrow 2.0.1.

**Comment by diamondspark** [comment]
@gncs Since sparrow is updated to 3.0.0, how to install Sparrow 2.0.1? I get following error when I try to do so...
```
 conda install -c conda-forge scine-sparrow-python=2.0.1Collecting package metadata (current_repodata.json): doneSolving environment: failed with initial frozen solve. Retrying with flexible solve.Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - scine-sparrow-python=2.0.1
